author:
  - name: Mickaël CANOUIL, *Ph.D.*
    email: mickael.canouil@rlille.fr
    url: https://mickael.canouil.fr/
institute: R Lille Meetup
picture: https://github.com/mcanouil.png

date: today

format:
  rlille-revealjs:
    theme: [_extensions/RLille/rlille/rlille.scss, assets/scss/custom-rlille.scss]
    logo: https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/rlille.svg
